#!/bin/bash

# CHANGE VARIABLES HERE!

WIRELESS_DEVICE=wlan0

# DO NOT CHANGE BELOW THIS LINE!

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
   echo "Example: sudo ./adhoc_desetup"
   exit 1
fi

echo "/***************************\\"
echo " * adhoc_desetup script *"
echo " * Kevin Alberts *"
echo "\***************************/"
echo ""
echo "Current settings: (edit the script with 'nano adhoc_desetup' to change) "
echo "Wireless device: "$WIRELESS_DEVICE
echo ""

echo -ne "Bringing down the wireless interface..."
ifconfig $WIRELESS_DEVICE down
tput cuf $(($(tput cols)-48))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "] "
echo -ne "Changing interface back to managed networks..."
iwconfig $WIRELESS_DEVICE mode Managed
tput cuf $(($(tput cols)-55))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "] "
echo -ne "Starting NetworkManager..."
service network-manager start &> /dev/null
tput cuf $(($(tput cols)-35))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "] "
echo -ne "Restarting NetworkManager to reconnect..."
sleep 1
service network-manager restart &> /dev/null
tput cuf $(($(tput cols)-50))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo -ne "] "
echo "You are now being connected to normal wireless communications."
